apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: booking-dev-auth
      context: .
      sync:
        manual:
          - src: apps/auth/src/**/*.ts
            dest: /app
      docker:
        dockerfile: infra/docker/dev-auth.Dockerfile
    - image: booking-dev-tickets
      context: .
      sync:
        manual:
          - src: apps/tickets/src/**/*.ts
            dest: /app
      docker:
        dockerfile: infra/docker/dev-tickets.Dockerfile
    - image: booking-dev-orders
      context: .
      sync:
        manual:
          - src: apps/orders/src/**/*.ts
            dest: /app
      docker:
        dockerfile: infra/docker/dev-orders.Dockerfile
    - image: booking-dev-client
      context: .
      docker:
        dockerfile: infra/docker/dev-client.Dockerfile
      sync:
        manual:
          - src: "apps/{client,auth,tickets,orders}/src/**/*.{js,ts,tsx}"
            dest: /app

  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
