apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: booking-dev-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: booking-dev-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: "src/**/*.{js,ts,tsx}"

  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
