version: "3.8"

services:
  postgres:
    container_name: test-postgres-orders
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
