import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";

import { CssBaseline } from "@mui/material";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import { AppToolbar } from "./ui/AppToolBar";
import { UserProvider } from "./context/user.context";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "EventPulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <AppRouterCacheProvider>
        <body>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <UserProvider>
              <AppToolbar />
              {children}
            </UserProvider>
          </ThemeProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
