apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-mongodb-auth
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - until nc -z auth-mongo-srv 27017; do echo waiting for mongodb; sleep 2; done
      containers:
        - name: auth
          image: booking-dev-auth:latest
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: GOOGLE_REDIRECT_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: JWT_KEY
            - name: AUTH_CREATE_ADMIN_HASH
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: AUTH_CREATE_ADMIN_HASH

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
