apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: booking-dev-client
          imagePullPolicy: IfNotPresent # Added this line for better control
          env:
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
            - name: NEXT_PUBLIC_GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: NEXT_PUBLIC_GOOGLE_REDIRECT_URI
            - name: NEXT_PUBLIC_BASE_URL
              value: "https://booking.dev"
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
