apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-jetstream-stream-config
  labels:
    app: nats-jetstream
data:
  stream.json: |
    {
      "name": "booking",
      "subjects": ["orders.*", "tickets.*"],
      "description": "Booking events stream",
      "retention": "limits",
      "discard": "old",
      "storage": "memory",
      "num_replicas": 1
    }
  ticketsConsumer.json: |
    {
      "durable_name": "tickets-service-durable",
      "description": "Durable consumer for tickets service",
      "stream_name": "booking",
      "filter_subjects": ["orders.*"],
      "deliver_policy": "all",
      "ack_policy": "explicit",
      "replay_policy": "instant",
      "max_ack_pending": 128
    }
  ordersConsumer.json: |
    {
      "durable_name": "orders-service-durable",
      "description": "Durable consumer for orders service",
      "stream_name": "booking",
      "filter_subjects": ["tickets.*"],
      "deliver_policy": "all",
      "ack_policy": "explicit",
      "replay_policy": "instant",
      "max_ack_pending": 128
    }
