apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: orders-postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: ORDERS_POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: ORDERS_POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: ORDERS_POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-srv
spec:
  type: ClusterIP
  selector:
    app: orders-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
