apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-redis
  template:
    metadata:
      labels:
        app: orders-redis
    spec:
      containers:
        - name: orders-redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          

---

apiVersion: v1
kind: Service
metadata:
  name: orders-redis-srv
spec:
  type: ClusterIP
  selector:
    app: orders-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: db