apiVersion: batch/v1
kind: Job
metadata:
  name: tickets-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command:
            - sh
            - -c
            - until nc -z tickets-postgres-srv 5432; do echo waiting for postgres; sleep 2; done
      containers:
        - name: migrate-db
          image: booking-dev-tickets:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_DB
          command:
            - bun
            - run
            - drizzle-kit:migrate-dev
